[package]
name = "multi-agent-simulation"
version = "0.1.0"
edition = "2021"


[dependencies]
neighbors = { git = "https://github.com/j-negro/cell-index-method", tag = "v1.0.1" }
rand = "0.8.5"
clap = { version = "4.1.13", features = ["derive"] }
anyhow = "1.0.70"
plotters = "0.3.4"
